global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'mysql'
    static_configs:
      - targets: [ 'db_exporter:9104' ]

  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis:9121' ]""